{
 "title": "COVID-19 by State",
 "time": { "from": "now-60d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "state",
    "label": "State",
    "query": "SHOW TAG VALUES on \"covid-19\" WITH KEY = \"state\""
   }
  ]
 },
 "panels": [
  {
   "title": "Total Cases in US",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "value",
     "query": "SELECT sum(\"cases\") FROM \"value\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Deaths in US",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "value",
     "query": "SELECT sum(\"deaths\") FROM \"value\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cases by State",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Deaths by State",
   "type": "stat",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Cases by State",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "value",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths by State",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "value",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Cases by State (Daily)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Number of Cases" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "value",
     "select": [
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  },
  {
   "title": "Deaths by State (Daily)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Number of Deaths" }
   ],
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "value",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "state", "operator": "=~", "value": "/^$state$/" }
     ]
    }
   ]
  }
 ]
}